### ISSUE TITLE
Publish timeout when a nats streaming server is restarted

### ISSUE THREAD

**Issue by rafsawicki** [nats-io/node-nats-streaming#101]
I'm experiencing timeout errors from a nats streaming client when a nats streaming server is restarted. I'm not sure if it's a matter of misconfiguration (a server is started in a docker container) or an error with a library itself. What can be done to avoid this problem?

For a reproduction scenario:

Start a nats streaming server using docker container
```bash
docker run -n natss -d -p 4222:4222 -p 8222:8222 nats-streaming
```

Run a sample publisher
```js
var stan = require('node-nats-streaming').connect('test-cluster', 'test');
stan.on('reconnecting', () => console.log('reconnecting'));
stan.on('reconnect', () => console.log('reconnect'));
stan.on('disconnect', () => console.log('disconnect'));

setInterval(() => {
  stan.publish('foo', 'Hello node-nats-streaming!', function(err, guid){
    if(err) {
      console.log('publish failed: ' + err);
    } else {
      console.log('published message with guid: ' + guid);
    }
  });
}, 3000);
```
Restart a nats streaming server container:
```bash
docker restart natss
```
Output:
```
published message with guid: S0C2ORNCLYBL7059JCLPET
published message with guid: S0C2ORNCLYBL7059JCLPKI
disconnect
reconnecting
reconnect
publish failed: Error: stan: publish ack timeout
publish failed: Error: stan: publish ack timeout
```

**Comment by rafsawicki** [comment]
It looks like I've tested with an older version - after updating my dependencies to the latest version I'm not experiencing this behavior anymore. Sorry for the confusion!

**Comment by kozlovic** [comment]
Regardless of the version, you are running a server without a persistent store, so no state will be recovered after the server restart. Actually with latest server and node client you should get a notification that the connection is no longer valid.

**Comment by rafsawicki** [comment]
@kozlovic It's very helpful - I didn't expect persistent store options to influence this. Thank you.
