### ISSUE TITLE
Localhost added to 'servers' list unnecessarily

### ISSUE THREAD

**Issue by PaulAcre88** [nats-io/node-nats-streaming#106]
Please close if I'm wrong, but I see localhost:4222 being added to the 'servers' list, in the options passed to node-nats. I can't follow the logic exactly but it seems to happen because I'm not setting a "url" option, so the url gets set to localhost (by default) and then that gets merged into the servers list..

Only a problem I noticed because I'm running 1 local and 1 remote server, and things were getting weird. Work-around was to populate 'url' with the same value I'm setting in 'servers', preventing it from being populated with the default value...

**Comment by aricart** [comment]
This is an issue for node-nats. Opening there.

**Comment by aricart** [comment]
@PaulAcre88 did a quick test to ensure we are not trying to add a default test somewhere.
```javascript
    it('shouldnt add localhost when servers are specified', function(done) {
        const nc1 = STAN.connect(cluster, nuid.next(), {
            servers: ['nats://localhost:' + PORT],
        });
        nc1.on('connect', function() {
            should(nc1.nc.servers.length).be.equal(1);
            done();
        });
    });
```

 I think the main issue is as you describe. You are running in a NATS cluster, and the NATS clustering protocol is indeed gossiping the localhost (which is valid), and thus added to the server list known to the underlying nats client. If your NATS clustering is correct, it should be possible for you to specify the localhost and still reach your STAN server (provided it is running remotely).

**Comment by aricart** [comment]
@PaulAcre88 if your cluster is not as I described, please feel free to reopen with additional information. Thank you!

**Comment by PaulAcre88** [comment]
Thanks. I have two distinct servers, one local and one remote. No clustering. And I have two clients running locally, each one intended for a different server. The client that is intended to connect only to the remote server is accidentally connecting to the local server too. Could be a weird setup, or an incorrect use of the 'server' option. But also seems unintuitive to me that the client would always try connecting to a server not explicitly listed...
