### ISSUE TITLE
[feature request] async subscribe callback

### ISSUE THREAD

**Issue by remorses** [nats-io/node-nats-streaming#107]
I s there a way to pass an asynchronous callback to subscribe?
```
    subscription.on('message', async (msg) => {
        await db.insert(msg.getData())
        console.log(msg.getSubject(), `[${msg.getSequence()}]`, msg.getData());
    });
```
Then the callbacks would run sequentially one after another.
I need to listen to the messages and block the other messages until i write to the database.

**Comment by remorses** [comment]
I finally found a way to sequentially pull messages.
I  am trying to implement an event sourcing system, a service will listen for events like 'ADDED_THING', 'REMOVED_THING' and will update a database.
It is important to get these messages sequentially to write the changes in order.
```javascript
const subscription = sc.subscribe(subject, queue_group, {
    ...sc.subscriptionOptions(),
    manualAcks: true,
    maxInFlight: 1
});

subscription.on('message', (msg) => {
    Promise.resolve(msg).then(
       async msg => {
            // write to db
            console.log(msg.getSubject(), `[${msg.getSequence()}]`, msg.getData());
            msg.ack()
       }
    )
});
```
The problem now is that this will become a slow consumer.

**Comment by aricart** [comment]
It shouldn't - if you have set maxInFlight to one, and also do `setAckWait(millis)` on the subscription, the server will patiently wait for you to ack once you have saved to your database.
