### ISSUE TITLE
Consider renaming `publishAsync` to `publish`

### ISSUE THREAD

**Issue by lekoder** [nats-io/node-nats-streaming#14]
Since, by default, most operations performed in node.js are asynchronous, there seems to be a convection node.js to name asynchronous methods without 'Async' postfix, ie. `fs.readFile` vs `fs.readFileSync`. Furthermore, popular Promise implementation [Bluebird](http://bluebirdjs.com/docs/getting-started.html)  provides promisification utility, which by default will append 'Async' to each promisified method, resulting in akwaryd `stan.publishAsyncAsync`.

While it is only a superficial issue, i would suggest considering renaming `publishAsync` method while library is still work-in-progress and there are no dependencies to be affected.

**Comment by aricart** [comment]
I agree with this. We try to keep the libs fairly close to each other in behaviour. But in this case it doesn't make sense.
