### ISSUE TITLE
Misnamed SubscriptionOption Method for StartPosition.TIME_DELTA_START

### ISSUE THREAD

**Issue by sfrooster** [nats-io/node-nats-streaming#17]
This line https://github.com/nats-io/node-nats-streaming/blob/master/lib/stan.js#L487

should be

`sr.setStartTimeDelta(retVal.opts.startTime);`

**Comment by aricart** [comment]
Thanks for the spotting. I added tests for the `setStartAtTimeDelta` and `setStartTime`.
