### ISSUE TITLE
Module naming in examples.

### ISSUE THREAD

**Issue by soulne4ny** [nats-io/node-nats-streaming#19]
Examples contain `require('stan')`, while npm finds the module as `node-nats-streaming`. So `require('stan')` does not find the module in `node_modules`.

Code in README and in `examples/` would better be consistent with end-user's point of view.

**Comment by aricart** [comment]
@soulne4ny Are you using typescript?

**Comment by soulne4ny** [comment]
@aricart, I'm using plain nodejs 6.6.

**Comment by aricart** [comment]
This is addressed by #20 as well.
