### ISSUE TITLE
When given clientID is duplicated, it complains on subject, not on clientID.

### ISSUE THREAD

**Issue by soulne4ny** [nats-io/node-nats-streaming#22]
When given `clientID` is duplicated, it does not fail on connect, but on subscribe. Traceback is
```
Error: Subject must be supplied
    at Object.<anonymous> (/app/node_modules/nats/lib/nats.js:70:23)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/app/node_modules/nats/index.js:1:80)
    at Module._compile (module.js:556:32)
```

**Comment by bkim54** [comment]
+1

**Comment by sfrooster** [comment]
Furthermore, it does not fail on publish...

**Comment by aricart** [comment]
This is bad bug. The error was not propagated, so the subject names used for various protocol entries were not set. After fix you should see the 'error' handler for the connection getting called, followed by a 'close' handler if the nats connection was created by the library.

**Comment by aricart** [comment]
npm is already updated with 0.0.14!

**Comment by jazoom** [comment]
I don't know if this is technically part of the same bug, but the exact same error message ("Subject must be supplied") is returned when trying to subscribe before the connection is ready.

**Comment by jazoom** [comment]
Nope. Like I said, it was fixed by not subscribing until the connection was ready. Both client and server were up to date because I'd only just installed them.

**Comment by aricart** [comment]
Ah - missed the waiting for connection bit.  - Yes you must wait for the connection to be ready before you invoke any of the streaming apis.

**Comment by jazoom** [comment]
>you must wait for the connection to be ready before you invoke any of the streaming apis

That would be a good error message. Certainly much more helpful than "Subject must be supplied".

**Comment by AaronFriel** [comment]
Are client IDs truncated anywhere? I am seeing this message in a production environment and wondering if there's an issue with long client IDs.

**Comment by aricart** [comment]
@AaronFriel client ids are not truncated on the client. How long are your ids?
