### ISSUE TITLE
Add Client Support for Subscription.Close()

### ISSUE THREAD

**Issue by sfrooster** [nats-io/node-nats-streaming#24]
This is/will be supported in the Server, needs to be implemented in the Client:

https://github.com/nats-io/nats-streaming-server/issues/182

**Comment by sfrooster** [comment]
@aricart Any idea when this might be implemented?

**Comment by sfrooster** [comment]
@aricart checking in once again on the status of this. As I'm aware, go, Java and csharp have now implemented so.... any idea?

**Comment by aricart** [comment]
This is high up on my list, but requires a bit of effort. Other projects are monopolizing my time. I'll dedicate Friday to it see if I can get it started.

**Comment by aricart** [comment]
@sfrooster I have done an initial pass for close(). give it a spin.
