### ISSUE TITLE
nodejs version requirement too strict

### ISSUE THREAD

**Issue by thegoleffect** [nats-io/node-nats-streaming#27]
The package.json requires node to be `"node": ">= .10.x"` does not work for the current or active LTS versions of node.

**Comment by aricart** [comment]
Hi @thegoleffect , there are two things that I am seeing:

- The version of node should be `">= 0.10.x"`

But also by looking at [LTS](https://github.com/nodejs/LTS) page, I am wondering whether you are asking to bump to 0.12, which is about to be bumped by 4.

Can you clarify?

Thanks!

**Comment by thegoleffect** [comment]
@aricart as of December 2016, v6 is now an active LTS major version.  The latest version for 6 is 6.9.2 which fails the ">= .10.x" which was present at the time in this project's package.json.

Your fix for #27 solves the problem. Thanks! 

Good to close this issue.
