### ISSUE TITLE
Error on large number of subscriptions

### ISSUE THREAD

**Issue by karteek-gamooga** [nats-io/node-nats-streaming#39]
@aricart 

I am trying to publish messages to 1 million subjects and subscribing to those subjects from another process. I get the following error: 
```
NatsError: Subject must be supplied
    at Client.publish (/root/node_modules/nats/lib/nats.js:1022:13)
    at Message.ack (/root/node_modules/node-nats-streaming/lib/stan.js:804:24)
    at Message.maybeAutoAck (/root/node_modules/node-nats-streaming/lib/stan.js:791:10)
    at Object.callback (/root/node_modules/node-nats-streaming/lib/stan.js:690:11)
    at Client.processMsg (/root/node_modules/nats/lib/nats.js:957:11)
    at Client.processInbound (/root/node_modules/nats/lib/nats.js:885:14)
    at Socket.<anonymous> (/root/node_modules/nats/lib/nats.js:468:12)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
```

Publisher code:
```
var stan = require('node-nats-streaming').connect('test-cluster', 'test',{maxPubAcksInflight: 1100000});
let total = 1000000;
stan.on('connect', function () {
  for(let i=0;i<total;i++)
  {
    stan.publish('foo'+i, 'Hello node-nats-streaming:' + i);
    if(i%1000 == 0)
      console.log(i);
    }
});
```

Subscriber code:
```
var stan = require('node-nats-streaming').connect('test-cluster', 'test3');

let total = 1000000;
let a = [];
let j = 0;
stan.on('connect', function () {
  for(let i=0;i<total;i++)
  {
    var opts = stan.subscriptionOptions();
    opts.setDeliverAllAvailable();
    opts.setMaxInFlight(1000000);
    opts.setDurableName('my-durable' + i);
    a.push(stan.subscribe('foo'+i, opts));
//    a[i].on('ready',function() {
      a[i].on('error', function (err) {
        console.log('subscription for ' + this.subject + " raised an error: " + err + '\n' + err.stack);
      });
      a[i].on('message', function (msg) {
        j += 1;
        if(j%1000 == 0){
          console.log(j);
          console.log('Received a message [' + msg.getSequence() + '] ' + msg.getData());
        }
//      });
    });
  }
});
```

Running nats streaming from a docker using: 
`docker run -p 4222:4222 -ti nats-streaming --max_channels 1000000 --max_subs 1000000`

Please help me out figuring the issue.

**Comment by karteek-gamooga** [comment]
Maybe related to #31?

**Comment by aricart** [comment]
What server version do you have?

**Comment by karteek-gamooga** [comment]
I am using version 0.3.8 which seems to be the latest version.

**Comment by aricart** [comment]
The fix to streaming is here: 75c0848f2a960d48b34e21ff365c78256a6acd67. The fix was generated on 1/31/2017, and 0.3.8 is from 1/19/2017. The fix is only on master, so you'll need to build your own version.

**Comment by karteek-gamooga** [comment]
Thanks @aricart . I will try it out.

On a side note, can I subscribe to a large number of subjects from a single process as above. When I do so I am only able to get the messages from the first ~5000 subjects. Are there any limits on the number of subjects I can subscribe to at a single point of time?

**Comment by aricart** [comment]
The node-nats library doesn't limit you. I am wondering if the server is timing out some of your subscriptions. As you know, node is single-threaded. You can try adding some error handlers, or starting the streaming server with the -SDV flag to see what the server is doing.

I wonder if you should be segmenting your subscriptions to a number of clients. Not sure of the wisdom to have 1M subscriptions on a single process.

**Comment by karteek-gamooga** [comment]
I have built the latest code from master and facing the same error. 
```
subscription for foo9997 raised an error: NatsError: Subject must be supplied
NatsError: Subject must be supplied
    at Client.publish (/root/node_modules/nats/lib/nats.js:1022:13)
    at Message.ack (/root/node_modules/node-nats-streaming/lib/stan.js:804:24)
    at Message.maybeAutoAck (/root/node_modules/node-nats-streaming/lib/stan.js:791:10)
    at Object.callback (/root/node_modules/node-nats-streaming/lib/stan.js:690:11)
    at Client.processMsg (/root/node_modules/nats/lib/nats.js:957:11)
    at Client.processInbound (/root/node_modules/nats/lib/nats.js:885:14)
    at Socket.<anonymous> (/root/node_modules/nats/lib/nats.js:468:12)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
```

**Comment by aricart** [comment]
You certain that the process you are running is the one from master? If that is the case then the server is still having the same issue. Node is single threaded, so if the server is sending messages after the protocol completes, there would be an ack subject and this trace is impossible. I'll revisit with @kozlovic

**Comment by ColinSullivan1** [comment]
@karteek-gamooga , regarding limits, you'll be bound by file descriptors and memory.  You'll want to make sure you've configured your OS/environment appropriately to allow for this, and perhaps disable swapping as well.

**Comment by aricart** [comment]
that formula always sneaks up. A little times a lot is huge. :)

**Comment by kozlovic** [comment]
Looked at the fix on the server and looks ok to me. Let's see if @karteek-gamooga make sure that it connects to master server (and not a running docker version that is still 0.3.8) and see if he can still reproduce.

**Comment by karteek-gamooga** [comment]
@kozlovic I can confirm that I pulled and compiled master and still seeing the error.

```
[28501] 2017/03/28 11:49:21.880716 [INF] Starting nats-streaming-server[test-cluster] version 0.3.9
```

May be it has to do with something with the large number of subscriptions. Before ~5000 subscribers all of them get the protocol message. After this none of the subscriptions receive the protocol messages.

**Comment by aricart** [comment]
@karteek-gamooga are there any errors showing up on the server? (start it with `SDV`)

**Comment by kozlovic** [comment]
I was about asking to run server with `-SD` (I suspect that `-SDV` may be a bit too verbose?). I am wondering if the client loop ever finishes? That is, is that test program giving the event loop a chance to process anything (including server HBs)?

**Comment by karteek-gamooga** [comment]
There are no errors on the server. These are the sample messages on the server:
```
[5193] 2017/03/28 18:32:45.965486 [DBG] STAN: [Client:test1] Added subscription on subject=foo8890, inbox=_INBOX.9DEJ6TEGP4I5004R836CKF
[5193] 2017/03/28 18:32:45.965614 [DBG] STAN: [Client:test1] Sending from beginning, subject=foo8891 seq=0
[5193] 2017/03/28 18:32:46.335467 [DBG] STAN: [Client:test1] Added subscription on subject=foo8891, inbox=_INBOX.9DEJ6TEGP4I52PKBGVPG9M
[5193] 2017/03/28 18:32:46.335495 [DBG] STAN: [Client:test1] Redelivering on ack expiration, subject=foo4824, inbox=_INBOX.9DEJ6TEGP4I5KES2Y3UM4P
[5193] 2017/03/28 18:32:46.335597 [DBG] STAN: [Client:test1] Redelivering on ack expiration, subject=foo4825, inbox=_INBOX.9DEJ6TEGP4I5SX62NK71YX
[5193] 2017/03/28 18:32:46.335630 [DBG] STAN: [Client:test1] Redelivering on ack expiration, subject=foo4826, inbox=_INBOX.9DEJ6TEGP4I50L883HXTG6
[5193] 2017/03/28 18:32:46.335645 [DBG] STAN: [Client:test1] Redelivering on ack expiration, subject=foo4827, inbox=_INBOX.9DEJ6TEGP4I5EABKW48GZI
``` 

I've reduced the loop counter to 1000 and everything works fine. I've increased it to 10000 and I get the first 5000 acks(and messages) and beyond that receiving messages before acks. After the initial 10000 subcriptions I dont do any work and it is not consuming any cpu so blocking the event loop might not be an issue.

**Comment by aricart** [comment]
One thing to keep in mind is that NATS will remove a client that is a slow consumer. By blasting on a loop you are creating that condition where messages are accumulating on one side and not getting drained (realize that the server is sending acks and other things that are not getting processed because no time is getting allowed in). NATS will notice that and effectively disconnect you.

I would make sure that your maxPubAcksInflight is not 1.1M. You are likely looking for a number that is in the thousands.

Can you take a look at the bench examples, and see how they yield to allow messages to move around.

**Comment by kozlovic** [comment]
Yes, so here is what would make it "work":
```
var stan = require('node-nats-streaming').connect('test-cluster', 'test3');
let total = 500000;
let subsBatchSize = 1000;
let numSubs = 0;
let a = [];
let j = 0;

stan.on('connect', function () {
  subSome();
});

function subSome() {
  var max = numSubs+subsBatchSize;
  for (i=numSubs; i<max;i++,numSubs++) {
    var opts = stan.subscriptionOptions();
    opts.setDeliverAllAvailable();
    opts.setDurableName('my-durable' + i);
    a.push(stan.subscribe('foo'+i, opts));
      a[i].on('error', function (err) {
        console.log('subscription for ' + this.subject + " raised an error: " + err + '\n' + err.stack);
        process.exit(1);
      });
      a[i].on('timeout', function (err) {
        console.log('subscription for ' + this.subject + " got timeout: " + err);
        process.exit(1);
      });
      a[i].on('message', function (msg) {
        j += 1;
        if(j%1000 == 0){
          console.log(j);
          console.log('Received a message [' + msg.getSequence() + '] ' + msg.getData());
        }
    });
  }
  stan.nc.flush(function() {
    if (numSubs < total) {
      process.nextTick(subSome);
    }
  });
}
```
The publisher code:
```
var stan = require('node-nats-streaming').connect('test-cluster', 'test');
let total = 500000;
let pubBatchSize = 1000;
let count = 0;
let callbackCount = 0;

stan.on('connect', function () {
  sendSome();
});

function sendSome() {
  var max = count+pubBatchSize;
  for(let i=count;i<max;i++,count++)
  {
    stan.publish('foo'+i, 'Hello node-nats-streaming:' + i, function (err, guid) {
      if (err) {
        console.log(i + " " + err);
        process.exit(1);
      }
      // console.log("recv ack for guid " + guid);
      callbackCount++;
      if (callbackCount === total) {
        stan.close(function() {
          process.exit(0);
        });
      } else {
        if (callbackCount === max) {
          process.nextTick(sendSome);
        }
      }
    });
    if(i%1000 == 0)
      console.log(i);
  }
}
```
I did run this with a separate `gnatsd` to better monitor the memory and cpu usage. I also made use of a feature in nats streaming in master to reduce the number of streaming server's internal subscriptions to receive application acks.
NATS server:
```
gnatsd
```
NATS Streaming Server:
```
nats-streaming-server -mc 0 -msu 0 -m 8222 -ack_subs 10 -ns nats://localhost:4222
```

Still, this is a lot of subscriptions (and I have reduce to 500,000 instead of 1M). You may want to split the load on different servers/processes.
