### ISSUE TITLE
Yarn installation complaining about node engine requirement in package.json

### ISSUE THREAD

**Issue by AlejandroEsquivel** [nats-io/node-nats-streaming#43]
There seems to be an error installing node-nats-streaming with yarn, it complains about the engine requirements in the package.json:

`error node-nats-streaming@0.0.14: The engine "node" is incompatible with this module. Expected version ">= .10.x".
`

My conjecture is that there should be a 0 before the .10.x, and while this may work on npm, yarn might not be handling this, and thinks the current node version doesn't meet the requirements for installation.

**Comment by sfrooster** [comment]
use yarn --ignore-engine

**Comment by aricart** [comment]
The current version of node-nats-streaming (0.0.25) declares that version as `0.10.0` to enable yarn to pickup node.js 6. See https://github.com/nats-io/node-nats-streaming/commit/eef8995a7c5c2c6b0874d06144f169a28ad20cea.

**Comment by brntsllvn** [comment]
Should be `yarn --ignore-engines` <---- don't forget the `s`
https://yarnpkg.com/en/docs/cli/install#toc-yarn-install-ignore-engines
