### ISSUE TITLE
Question on Stan.isClosed()?

### ISSUE THREAD

**Issue by soulne4ny** [nats-io/node-nats-streaming#44]
Hi!

Is `isClosed()` true always then there is no connection?
I mean, could it be that `isClosed()` is false and `this.nc.connected` is false as well?
https://github.com/nats-io/node-nats-streaming/blob/4b9af61fa7e0f8574e53c4304b123202edf84c5d/lib/stan.js#L100

Regards
Alex

**Comment by aricart** [comment]
Are you providing your own nats connection to the client rather than have the client use one that it creates?

**Comment by aricart** [comment]
The nats connection is internally closed (if the connection is owned by the library) when there's an error during connection or close() is called. The library's reference to the nats connection is deleted before the actual call to close happens. I see the possibility of the opposite condition that you are asking about.

**Comment by soulne4ny** [comment]
> Are you providing your own nats connection to the client rather than have the client use one that it creates?
No

**Comment by aricart** [comment]
is it possible that the nats server is detecting a slow consumer and it is killing the connection for the client?

**Comment by soulne4ny** [comment]
> is it possible that the nats server is detecting a slow consumer and it is killing the connection for the client?

I don't know.

**Comment by aricart** [comment]
I want to bet $1 that this is the case.

**Comment by soulne4ny** [comment]
So,`isClosed()`  false and `this.nc.connected` false seems possible.

**Comment by aricart** [comment]
Yes - if the library didn't initiate the close. See https://github.com/nats-io/node-nats-streaming/blob/master/lib/stan.js#L285 does this:

`  this.nc.on('close', function() {
    that.emit('close');
  });
`
Note that while it is propagating the event, it is not invalidating the reference. So isClosed() would return false, even if the nats connection was closed.

**Comment by aricart** [comment]
Opening an issue to remove the isClosed() method from the API. As it currently it is telegraphing the state of the nats connection, but in the case of stan it is a function of the state of the stan protocol (ie is closed should only be true if a close request was sent to the streaming server and the server didn't return an error).
