### ISSUE TITLE
Can I use nats streaming as task queue?

### ISSUE THREAD

**Issue by zhaoyao91** [nats-io/node-nats-streaming#49]
Say, 
- if there are more than 1 workers in a group, only one will receive the task (ok, it's implemented)
- if there is no listener for a task, the it will be cached and received by the first online listener(not sure about this)

**Comment by aricart** [comment]
Yes this is exactly what it is supposed to do

- Streaming server will store all messages published to the streaming API into a channel (no subscribers need yet to exist)
- When a subscriber subscribes to a subject, messages in the channel are played back.
- If you have subscribers in a queue group, a single subscriber from that queue is selected to receive the message. Non-queue subscribers get all messages in the channel.

**Comment by zhaoyao91** [comment]
thanks

**Comment by jscottsf** [comment]
I ran across this issue in search for an answer...

I'm also trying to use this for a task queue. Furthermore, I'm ack'ing the task request after the task is completed. However, with setMaxInFlight(1), messages are delivered in their proper order, and hence, you are limited by your slowest task worker in the group.

If I ack earlier, then my message handler gets called right away and multiple invocations are handled simultaneously by the same worker.

Seeking a good design pattern for this.
