### ISSUE TITLE
Waiting for a subscription to be ready

### ISSUE THREAD

**Issue by sschick-prognos** [nats-io/node-nats-streaming#50]
In tests, I want to be able to wait for a subscription to be listening before I send a message. I don't want to use `startWithLastReceived` because then I could see messages from past tests. Is there an event that I can wait on to guarantee that a subscription is up and running?

**Comment by aricart** [comment]
@sschick-prognos  there's no event emitted when the subscription becomes active.

There are a couple of things that you can do:

- Start a test server with a mem-store, you won't have to worry about previous messages. Look into the repo for node-nats-streaming it has some utility code that you can copy for starting servers for tests.

- You can use the [nuid](https://github.com/nats-io/node-nuid) and generate unique channels for your tests, and then you can simply subscribe to the last message. You'll have to agree on the subject but you should be able to do this when you generate the testing with a `before()` type function. Again take a look at our test for an idea.

**Comment by sschick-prognos** [comment]
Is there a reason this event can't exist? It would be really useful in terms of avoiding extra state.

**Comment by aricart** [comment]
@sschick-prognos you may be able to achieve what you want by starting your subscription with a start position with a start delta of 0. Which means with messages sent now or in the future. You'll still need to coordinate your publisher. One way that you could do this is to send a flush() to your NATS connection. This will insure that the NATS client has processed all in-flight sends (including your subscription), and then start sending messages. But as you can tell from this description this is more complicated than the alternative below.

I would instead generate a random subject name, publish to the subject, and subscribe to the subject. This approach would be simpler and provide with a sane environment where no other messages are in the channel except for those that you sent for this session.
