### ISSUE TITLE
Access to msg.guid from subscriber

### ISSUE THREAD

**Issue by holem** [nats-io/node-nats-streaming#52]
Hello! 
First of all, thank you for your product, it's really cool.

The issue is quite simple. On the publisher side we have `guid` of the published message. How can we access the same `guid` on the subscriber's side when message is receiving?

Thanks in advance.

**Comment by aricart** [comment]
@holem, the guid for a published message allows the library to map messages to acknowledgments, and invoke the correct callback for the message. Once the server has the message it is assigned a sequence number which is what subscribing clients are able to see or query for.

**Comment by holem** [comment]
@aricart Thank your for fast reply. It turns out that the server knows nothing about the guid and it used only by the library? In this case i can't find use case when the guid would be useful. 

Afaiu, having the same "id" (sequence or whatever) on both ends would be useful in some cases, but having different "id" makes them meaningless. Anyway, even without any "id", highly performant messaging bus is still great as a component for distributed application.

**Comment by aricart** [comment]
@holem yes the GUID is mostly for internal library use but you can use it for client purposes.
When you publish the message, the GUID is returned from `publish`. If you provided an ackHandler, the handler will be called with that GUID when the client receives confirmation that the server received the message - for example, if you needed to ensure that a message is delivered to the server, the client could go through the effort of persisting the message payload and keying it to the guid. In case of a crash the client could republish the message. This, of course, would also require for messages to be idempotent. On getting an ack, the client could perform cleanup tasks.

**Comment by holem** [comment]
@aricart, ok, thanks! i think this question issue can be closed.
