### ISSUE TITLE
Exposing underlying NATS conn

### ISSUE THREAD

**Issue by loremaps** [nats-io/node-nats-streaming#56]
Basically the same issue with nats-io/go-nats-streaming#67
Is there a way to get the underlying connection status?

**Comment by aricart** [comment]
You can pass a nats connection when creating the streaming client, the option is called `"nc"`. Alternatively, you can try accessing the `nc` property of the streaming client. Note that if you reference the `nc` directly, future releases of the library could break your code.

If you pass your own connection to the client, the ultimate closing of the connection is your responsibility - Nats connections created by the library are closed when `close()` is called.

**Comment by loremaps** [comment]
@aricart thank you for the quick response and the suggestions. Please feel free to close the issue if there is there is no plan to make it similar to the go client. Thanks again!
