### ISSUE TITLE
Cannot set property 'expected' of undefined

### ISSUE THREAD

**Issue by tsiage** [nats-io/node-nats-streaming#58]
Hello,

We are experiencing the following error with "nats" version 0.8.0:

/home/gts/src/test/nats/node_modules/nats/lib/nats.js:1292
    sub.expected = expected;
                 ^

TypeError: Cannot set property 'expected' of undefined
    at Client.timeout (/nats/node_modules/nats/lib/nats.js:1292:18)
    at Stan.subscribe (/nats/node_modules/node-nats-streaming/lib/stan.js:530:11)
    at Stan.<anonymous> (/nats/nats.js:82:27)
    at Stan.emit (events.js:127:13)
    at Object.callback (/nats/node_modules/node-nats-streaming/lib/stan.js:281:12)
    at Object.callback (/nats/node_modules/nats/lib/nats.js:1451:22)
    at Client.processMsg (/nats/node_modules/nats/lib/nats.js:1039:17)
    at Client.processInbound (/nats/node_modules/nats/lib/nats.js:968:24)
    at Socket.<anonymous> (/nats/node_modules/nats/lib/nats.js:502:16)
    at Socket.emit (events.js:127:13)

**Comment by aricart** [comment]
@tsiage, in the interim for compatibility with the node-streaming please set the option `useOldRequestStyle` option to `true`.

**Comment by aricart** [comment]
@tsiage  thanks for reporting the issue. I have fixes on both node-nats and node-nats-streaming.

**Comment by aricart** [comment]
npm will update as soon as the outstanding PR for 0.8.2 is reviewed.

**Comment by aricart** [comment]
@tsiage  npm 0.8.2 solves the issue without any changes on the stan client.

**Comment by tsiage** [comment]
@aricart thank you for your super fast fix!

**Comment by jscottsf** [comment]
Having this same problem under:

* node-nats-streaming 0.0.26
* nats-streaming-server version 0.8.0-beta via Docker

Any insights?

**Comment by aricart** [comment]
@jscottsf the issue is the nats library on the client. Need to upgrade to nats v0.8.2 on the node-nats-streaming clients.

**Comment by jscottsf** [comment]
@aricart Sorry to be an idiot here. So it seems nats-streaming-server-v0.8.0-beta cannot be used then? Should we move to nats-streaming-server-v0.7.2? Not available in Docker, but we can define our own container.

**Comment by aricart** [comment]
@jscottsf this doesn't have anything to do with the server version. This is the node-nats-streaming client exposed a bug in the v0.8.0 of node nats. This is strictly a client issue. I am actually about to open a PR request that clamps the version of the library - give me a few.

**Comment by kozlovic** [comment]
@jscottsf Regarding docker images, previous versions are always available. You just need to pull with specific tag. For instance.
```
docker pull nats-streaming:0.7.2
```
But as @aricart mentioned, the issue is not with the server here.

**Comment by jscottsf** [comment]
You're all awesome. Thank you!
