### ISSUE TITLE
Recommended subject count

### ISSUE THREAD

**Issue by chenmarko** [nats-io/node-nats-streaming#63]
Hello,
Is there any recommended limit to subject count using nat-streaming.
Specifically, we're looking to support 10-20k online users. We wish to have subjects corresponding to changes in their state. We'll it be ok to have a dedicated channel for each user or will it be better to have a single channel routing all users changes and do the filtering on the app level?

Thanks
Chen

**Comment by aricart** [comment]
@chenmarko this is the issue repo for node-nats-streaming. Your question should go here:
https://github.com/nats-io/nats-streaming-server/issues.

@kozlovic may have additional comments.

A few things to clarify when you move the issue:

-  Are you only interested in the current user state? - ie the last thing that they updated or do you need the 'log' of all their state changes?

- If this is 'online' session, this effectively means that the streaming channels are only used for the session, after the session ends the store will have a lot of stale data. If this case, I question is whether this should be on nats-streaming at all. Likely plain NATS would be better. If anything likely the streaming server should be configured to only hold messages for a specific amount of time.

**Comment by kozlovic** [comment]
To add to Alberto's comments, depending on what type of stores you are planning to use, the file store requires several file descriptors per channel, although there is an option to limit the use of opened file descriptors (at the expense of performance).

**Comment by aricart** [comment]
@chenmarko - I am closing this issue since really it is a general question about NATS Streaming scalability.
