### ISSUE TITLE
Handling of NATS client `json` option

### ISSUE THREAD

**Issue by wallyqs** [nats-io/node-nats-streaming#64]
Currently the `json` from the nats client is being picked up (here: https://github.com/nats-io/node-nats-streaming/blob/ebf4ff876651b252b8e4807cf6d7e3770253ab73/lib/stan.js#L168), but maybe it should not be allowed/error instead since NATS Streaming uses Protocol Buffers?

**Comment by aknuds1** [comment]
It would be helpful if this option were ignored or rejected via an exception, as it leads to a mysterious error when node-nats-streaming tries to parse the message.

**Comment by aricart** [comment]
I don't think we need to throw an error but it should be a no-op.
