### ISSUE TITLE
No message events when connecting with new client id

### ISSUE THREAD

**Issue by david-hex** [nats-io/node-nats-streaming#68]
Using version "node-nats-streaming": "0.0.28" and node v8.9.4 
I'm running into an issue where messages do not come through until I connect again with a previously used client id.  I'm unable to get the following code to work as I would expect. It only works if i use a consistently named client id. 

```
  function randomClientId () {
    return Math.floor(Math.random() * 9999).toString()
  }

  async function run(){
    const a = NATSS.connect('test-cluster',randomClientId())
    const b = NATSS.connect('test-cluster',randomClientId())

    await new Promise(res=>a.on('connect',res))
    await new Promise(res=>b.on('connect',res))
 
    b.subscribe('test').on('message',(msg)=>{
      //this never fires
      console.log(msg.getData())
    })
  
    a.publish('test','test',(err,guid)=>{
      if(err) console.log(err)
    })  
  }

  run()
```

**Comment by david-hex** [comment]
after looking through your tests, it looks like subscription options are required for any data to start coming through. Is this the intended behavior?

**Comment by aricart** [comment]
@david-hex The default subscription options created will have zero values or default values. See SubscriptionOptions(). This means that `startPosition` will be `NEW_ONLY`, matching your observations (which is also correct since the stream log could contain millions of messages).
