### ISSUE TITLE
Event for disconnection is not mapped

### ISSUE THREAD

**Issue by chris-verclytte** [nats-io/node-nats-streaming#71]
Hello,

I can see in the library that the "disconnect" event from NATS server is not mapped (like other ones [here](https://github.com/nats-io/node-nats-streaming/blob/master/lib/stan.js#L304)).
Is this intended ?

**Comment by aricart** [comment]
Yes it is an oversight.

**Comment by Qwerios** [comment]
Just a heads up I'm now seeing a disconnect before my initial connect. I had some logic in disconnect handling that incorrectly triggered due to this change. Thats all on my code but just wanted to mention it here for other people (and google) to find it.

**Comment by aricart** [comment]
The `disconnect` handler is called whenever the stream is closed - which will happen when you are connected and the stream closes or if you try to connect but the connection fails.

Given this test:
```javascript
 var stan = STAN.connect(cluster, nuid.next(), {'url': 'nats://localhost:' + PORT, 'reconnectTimeWait': 1000});

      var notifications = [];

      stan.on('connect', function () {
        notifications.push('CONNECT');
        setTimeout(function () {
            stan.subscribe("are.you.there", function (m) {});
        }, 2000);
        setTimeout(function () {
            ssc.stop_server(server);
        }, 0);
      });

      stan.on('disconnect', function() {
          notifications.push('DISCONNECT');
      });

      stan.on('reconnecting', function() {
          notifications.push('RECONNECTING');
      });

      stan.on('reconnect', function() {
          notifications.push('RECONNECT');
          console.log(notifications.join(','));
          done();
      });

      stan.on('timeout', function (err) {
          // restart the server for others
          startServer(()=>{});
      });
```

The sequence generated looks like this:
`CONNECT,DISCONNECT,RECONNECTING,DISCONNECT,RECONNECTING,DISCONNECT,RECONNECTING,DISCONNECT,RECONNECTING,DISCONNECT,RECONNECTING,RECONNECT`

**Comment by Qwerios** [comment]
I'm pretty sure its code on my end somewhere but the behaviour is triggered since the fix was deployed. Could also be related to how I deploy with kubernetes, etc. It's just an FYI your update looks sound

**Comment by soulne4ny** [comment]
The same for me. I get it in a docker's container. When a container is created and started it connects to the server, but receives no messages. Once restarted it works well.
