### ISSUE TITLE
AssertionError: Failure: Type not convertible to Uint8Array.

### ISSUE THREAD

**Issue by marcoreni** [nats-io/node-nats-streaming#73]
Hello,

I'm receiving the following error while closing a connection.

I'm still investigating the root cause, but I tried to debug this specific stack and it seems that https://github.com/google/protobuf/issues/1319#issuecomment-286542948 solves the issue

```
AssertionError: Failure: Type not convertible to Uint8Array.
    at new goog.asserts.AssertionError (/usr/src/shared/node_modules/google-protobuf/google-protobuf.js:98:603)
    at Object.goog.asserts.fail (/usr/src/shared/node_modules/google-protobuf/google-protobuf.js:100:89)
    at Object.jspb.utils.byteSourceToUint8Array (/usr/src/shared/node_modules/google-protobuf/google-protobuf.js:248:257)
    at jspb.BinaryDecoder.setBlock (/usr/src/shared/node_modules/google-protobuf/google-protobuf.js:314:264)
    at new jspb.BinaryDecoder (/usr/src/shared/node_modules/google-protobuf/google-protobuf.js:312:486)
    at Function.jspb.BinaryDecoder.alloc (/usr/src/shared/node_modules/google-protobuf/google-protobuf.js:313:207)
    at new jspb.BinaryReader (/usr/src/shared/node_modules/google-protobuf/google-protobuf.js:331:433)
    at Function.proto.pb.CloseResponse.deserializeBinary (/usr/src/shared/node_modules/node-nats-streaming/lib/pb/protocol_pb.js:2642:16)
    at Object.callback (/usr/src/shared/node_modules/node-nats-streaming/lib/stan.js:338:38)
    at Object.callback (/usr/src/shared/node_modules/nats/lib/nats.js:1474:26)
```

**Comment by marcoreni** [comment]
@aricart I'm running 0.0.28 . If this has already been solved by more recent releases we can safely close this, sorry for the confusion.

**Comment by aricart** [comment]
Excellent!

**Comment by marcoreni** [comment]
Hello @aricart , I upgraded node-nats-streaming to v0.0.41 but I'm still receiving the error in some cases.

I saw that in https://github.com/nats-io/node-nats-streaming/commit/08b648e6fc8518ffbb9ad47fbcbe48ad7449b9b0 `new Buffer()` became `Buffer.from`, but the Buffer => Array conversion is still `.toByteArray()` instead of `Array.from` as stated in the related issue.

Can you please check?

**Comment by aricart** [comment]
hi @marcoreni - could you please add a current stack trace that matches the your current npm/master? - I take it that your exception is failing here:

[ var cr = proto.CloseResponse.deserializeBinary(Buffer.from(msgOrError, 'binary').toByteArray());](https://github.com/nats-io/node-nats-streaming/blob/21c46a75986a0a76ce818de3aaaafdf538b3fc65/lib/stan.js#L350)

Also can you tell me:

- if you are providing your own nats client or using the default.
- what are the options that you set on your client.

Thanks,

/a

**Comment by aricart** [comment]
Also what kind of payloads are you sending around (can you give me a test). Thanks!

**Comment by aricart** [comment]
Just doing a local test that simulates the serialization/deserialization:

```
      // create the protobuf object serialize it to buffer
      let cr = new proto.CloseResponse();
      cr.setError("foo");
      let bm = Buffer.from(cr.serializeBinary());

      // nats will decode the message into a binary string - simulate that
      let bs = bm.toString("binary");

      // this is the parsing that happens on the handler for the close request
      let bm2 = Buffer.from(bs, 'binary');
      let out = proto.CloseResponse.deserializeBinary(bm2.toByteArray());
      out.getError().should.be.equal("foo");
```

I don't reproduce any errors.

Because the error you are experiencing is a flapper, I am willing to try an opt-in fix where you set an option `protobufFix` to `true` on the client. The `toByteArray()` would change to:

```
Buffer.prototype.toByteArray = function() {
  return protobufFix? Array.from(this) : Array.prototype.slice.call(this, 0);
};
```

**Comment by wuyezhiyu** [comment]
I have seen this problem,becouse i did not set the **binaryType** of my websocket object in js code.

ws = new WebSocket("ws://127.0.0.1:8080/ws");
ws.onopen = function(){
...
**ws.binaryType = 'arraybuffer';**
...
}

it is fixed when add      ws.binaryType = 'arraybuffer';

**Comment by aricart** [comment]
> I have seen this problem,becouse i did not set the **binaryType** of my websocket object in js code.
> the data from my service is decode into **Blob** object by default
> 
> ws = new WebSocket("ws://127.0.0.1:8080/ws");
> ws.onopen = function(){
> ...
> **ws.binaryType = 'arraybuffer';**
> ...
> }
> 
> it is fixed when i add ws.binaryType = 'arraybuffer';
> hope i can help anyone

Stan is a node library, there's no websocket support.
