### ISSUE TITLE
Reconnect subscription

### ISSUE THREAD

**Issue by puckey** [nats-io/node-nats-streaming#80]
When I turn the nats-streaming server on and off, the node-nats-streaming client reconnects. However, the subscription does not continue sending `message` events. Neither does it send an `error` event or any other events as far as I can see.

**Comment by aricart** [comment]
Are you running a server that uses persistence (FILE) ? or a memory based one?

**Comment by aricart** [comment]
This may be useful. https://github.com/nats-io/go-nats-streaming#advanced-usage

Note that the node client doesn't yet implement the ConnectionLostHandler.

**Comment by puckey** [comment]
I am using FILE based persistence.

When the server goes down, I am receiving `disconnect` events from stan. 11 in total after the server is turned off – after which reconnecting no longer happens:
```js
var stan = require('node-nats-streaming').connect(cluster_id, client_id, server);
stan.on('disconnect', function(reason) {
    console.log('disconnect', reason);
});
```

I expected just the one disconnect event, since I have not reconnected to the server in between. 

According to your link "When no NATS connection is provided to the Connect() call, the library creates its own NATS connection and will now set the reconnect attempts to "infinite", which was not the case before.". Is this the case in the Node client also? My client no longer reconnects after 11 disconnect events.

If I understand correctly, I will need to
- stan.on `disconnect` destroy current subscriptions
- stan.on `reconnect` recreate subscriptions from scratch

This causes quite some complexity on the user side. For most use cases I can think of (for subscriptions at least), I could imagine wanting to automatically reconnect subscriptions when the server comes back online.

**Comment by aricart** [comment]
Great - I am going to close this issue if you find something else please reopen.

**Comment by mbaranovski** [comment]
Hi @aricart, as I understand to make `node-nats-streaming` to constantly try to reconnect I need to specify `maxAttempts=-1`, `waitOnFirstConnect=true` - with other options as defaults it tries to reconnect about 7-8 times and I receive `connection_lost` event.
Looking at the stan.js code, the line which is preventing the nats-streaming to keep reconnecting is: https://github.com/nats-io/stan.js/blob/master/lib/stan.js#L357

If I set `stanMaxPingOut` to let's say `999` it will keep reconnecting until maxpingout reaches 999.
Is it correct behaviour and I'm missing something?

Thanks
