### ISSUE TITLE
Starting with the last received

### ISSUE THREAD

**Issue by TomasRup** [nats-io/node-nats-streaming#85]
Hi,

How should I subscribe so if my subscriber fails (is down for an hour) and once it's back, I want to start from the last received message?

Is it possible without storing the id of the last received message?

**Comment by aricart** [comment]
@TomasRup the start parameter specifies that behaviour. The server remembers the last message that the client ack'ed, checkout https://github.com/nats-io/node-nats-streaming#subscription-start-ie-replay-options

**Comment by aricart** [comment]
@TomasRup take a look at durable subscriptions. The durable subscription will resume where the client left off.
 https://github.com/nats-io/node-nats-streaming#subscription-start-ie-replay-options

**Comment by aricart** [comment]
Closing this issue. Let me know if you have additional questions.

**Comment by TomasRup** [comment]
@aricart I'm sorry for replying so late.

Like, in the doc you gave me (https://github.com/nats-io/node-nats-streaming#subscription-start-ie-replay-options), none of options really solve this:

If I set `setStartWithLastReceived`, it does not start from the last received, this is the output of my sample app:
```
➜  nats-playground node subscriber.js 
Msg: {"pid":88798,"text":"text","bool":true} ; 1
Msg: {"pid":88798,"text":"text","bool":true} ; 2
Msg: {"pid":88798,"text":"text","bool":true} ; 3
Msg: {"pid":88798,"text":"text","bool":true} ; 4
Msg: {"pid":88798,"text":"text","bool":true} ; 5
Msg: {"pid":88798,"text":"text","bool":true} ; 6
Msg: {"pid":88798,"text":"text","bool":true} ; 7
Msg: {"pid":88798,"text":"text","bool":true} ; 8
Msg: {"pid":88798,"text":"text","bool":true} ; 9
Msg: {"pid":88798,"text":"text","bool":true} ; 10
Msg: {"pid":88798,"text":"text","bool":true} ; 11
Msg: {"pid":88798,"text":"text","bool":true} ; 12
^C
➜  nats-playground node subscriber.js
Msg: {"pid":88798,"text":"text","bool":true} ; 17
Msg: {"pid":88798,"text":"text","bool":true} ; 18
Msg: {"pid":88798,"text":"text","bool":true} ; 19
Msg: {"pid":88798,"text":"text","bool":true} ; 20
```

i.e. it doesn't start with the last received.

Here is my config:
```
  const options = stream
    .subscriptionOptions()
    .setStartWithLastReceived();

  const subscription = stream.subscribe('HELLO_WORLD', options);
```

All other solutions (`setStartAtSequence`/`setStartTime`/`setStartAtTimeDelta`), would require me to store last consumed id. I don't want to do this 🤓 

And `setDeliverAllAvailable` doesn't solve this.

**Comment by aricart** [comment]
@TomasRup hi Tomas, it starts with the last ack'ed message. The library acknowledged 13-16, but your app crashed(?) before it processed them. For your application, I think you'll want to work on a manual ack'mode, but that will introduce additional complexities.

Take a look at https://github.com/nats-io/node-nats-streaming#message-acknowledgements-and-redelivery

Note that if your application takes a long time to respond to the acknowledgment. Take a look at https://github.com/nats-io/node-nats-streaming#message-acknowledgements-and-redelivery. More specifically https://github.com/nats-io/node-nats-streaming#message-acknowledgements-and-redelivery.

**Comment by kozlovic** [comment]
@TomasRup I think @aricart mentioned that you should be using durable subscription if you want the server to maintain position for you. He pointed to the subscription start option, but if you look just the paragraph after that: https://github.com/nats-io/node-nats-streaming#durable-subscriptions

**Comment by aricart** [comment]
The key to the durable subscription is:
```stan.on('connect', function () {
  // Subscribe with durable name
  var opts = stan.subscriptionOptions();
  opts.setDeliverAllAvailable();
  -----> opts.setDurableName('my-durable');

  var durableSub = stan.subscribe('foo', opts);
  durableSub.on('message', function(msg) {
    console.log('Received a message: ' + msg.getData());
  });```

**Comment by aricart** [comment]
@kozlovic thanks for catching that.

**Comment by TomasRup** [comment]
@kozlovic @aricart but the `durable` abstraction you mentioned does not help when the consumer crashes. 

If my config is:
```js
  const options = stream.subscriptionOptions();
  options.setDeliverAllAvailable();
  options.setDurableName('test-durability');
```
Then I'm just getting all available.

I believe durable thing works only if I stop listening and then resume, but not if I exit the node instance that runs the listener? Moreover, how would it would it work in scaled environment - let's say I have 10 listeners, all hosted, e.g. on AWS, AWS goes down - where do they start listening? 😄

**Comment by kozlovic** [comment]
The durable option instructs the *server* to keep track of where the subscription is at. The durable name + client ID form a unique name, you can only have 1 of this pair, otherwise you would need to use durable queue subs, but that distribute the messages across all members of the same group.

When you have a durable (assuming you use the same client ID on restart, otherwise you would simply create new durables), if it crashes or exit cleaning (but does not call unsubscribe()), then the server will resent messages that have not been acknowledged (if any) and then new ones. Not old ones. 
You can also read about durables in the server's readme: https://github.com/nats-io/nats-streaming-server#durable
