### ISSUE TITLE
sending structured data possible?

### ISSUE THREAD

**Issue by JannikZed** [nats-io/node-nats-streaming#86]
Is it planned (or already possible) to send nats-streaming messages as structured data in the same way as `node-nats` is supporting it here: https://github.com/nats-io/node-nats-examples/blob/master/src/publisher_samples.js#L25-28

**Comment by aricart** [comment]
already possible. The payload for a message is anything you want.

**Comment by JannikZed** [comment]
Are you sure? I get `AssertionError: Failure: Cannot coerce to Uint8Array: object` on trying to send an object to the queue ..

**Comment by aricart** [comment]
Apologies for not being clearer. Nats-streaming messages are data agnostic, the messages themselves are protobuf messages, so the underlying data is an Uint8Array. You can provide a Uint8Array, string or Buffer only. 

If you want to send JSON you'll have to encode on publish and decode on the subscription handler :

```
   var sub = stan.subscribe(subj, opts);
   sub.on('message', function (msg) {
        var v = JSON.parse(msg.getData());
              ...
   }
  stan.publish(subj, JSON.stringify({a: "b"}));
```
