### ISSUE TITLE
Disable reconnect attempts

### ISSUE THREAD

**Issue by akoenig** [nats-io/node-nats-streaming#98]
Hello there 🙂, 

I want to pass the option that the underlying NATS client should not try to reconnect. I just thought that I can pass the options via `.connect`, but the TypeScript type definition file doesn't contain all available options.

Any pointer in the right direction is highly appreciated 🙂

**Comment by akoenig** [comment]
It seems like the type definitions are outdated. Could that be the case here?

**Comment by aricart** [comment]
You are absolutely correct - I had start work on update there for pingInterval, and maxPingOut. Let me add all the others.

**Comment by akoenig** [comment]
Awesome. Thanks for the quick fix 😊
